language: r

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - R_CHECK_TIMINGS_="0"

